// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://babnkamhsuvinoyicjjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhYm5rYW1oc3V2aW5veWljamp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzc0NTgsImV4cCI6MjA2NjYxMzQ1OH0.AiDJv5h4sxX4_9YjuuMVKLD7XDnvzpxNvGEhSZE4dbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);